// Code generated by goctl. DO NOT EDIT.
package types

type BrandAddResp struct {
	Id int64 `json:"id"`
}

type BrandDelReq struct {
	Ids string `path:"ids"`
}

type BrandForm struct {
	Id     int64  `json:"id"`     // 主键
	ShopId int64  `json:"shopId"` // shopID
	Name   string `json:"name"`   // 品牌名称
	Logo   string `json:"logo"`   // LOGO图片
	Sort   int64  `json:"sort"`   // 排序
}

type BrandGetReq struct {
	Id int64 `path:"id"`
}

type BrandListReq struct {
	Keywords string `form:"keywords,omitempty,optional"`
	ShopId   int64  `form:"shopId,default=1"` // shopID
	PageNum  int64  `form:"pageNum,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
}

type BrandListResp struct {
	List  []PmsBrand `json:"list"`
	Total int64      `json:"total"`
}

type BrandOptionsReq struct {
	Id int64 `path:"id"`
}

type CaptchaResp struct {
	CaptchaBase64 string `json:"captchaBase64"`
	CaptchaKey    string `json:"captchaKey"`
}

type CategoryAddResp struct {
	Id int64 `json:"id"`
}

type CategoryDelReq struct {
	Ids string `path:"ids"`
}

type CategoryGetReq struct {
	Id int64 `path:"id"`
}

type CategoryOptionsReq struct {
	Id int64 `path:"id"`
}

type FileUpload struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}

type GoodsDelReq struct {
	Ids string `path:"ids"`
}

type GoodsEditRep struct {
	Id          int64                   `json:"id,optional"`
	ShopId      int64                   `json:"shopId"`
	CategoryId  int64                   `json:"categoryId"`
	BrandId     int64                   `json:"brandId"`
	Name        string                  `json:"name"`
	OriginPrice int64                   `json:"originPrice"`
	Price       int64                   `json:"price"`
	PicUrl      string                  `json:"picUrl,optional"`
	SubPicUrls  []string                `json:"subPicUrls,optional"`
	Unit        string                  `json:"unit,default=个"`
	Description string                  `json:"description"`
	Detail      string                  `json:"detail"`
	Status      int64                   `json:"status,default=1"`
	SkuList     []PmsGoodsFormSku       `json:"skuList,optional"`
	AttrList    []PmsGoodsFormAttribute `json:"attrList,optional"`
	SpecList    []PmsGoodsFormAttribute `json:"specList,optional"`
}

type GoodsEditResp struct {
	Id int64 `json:"id"`
}

type GoodsGetReq struct {
	Id int64 `path:"id"`
}

type LoginReq struct {
	UserName    string `json:"username"`
	Password    string `json:"password"`
	CaptchaCode string `json:"captchaCode"`
	CaptchaKey  string `json:"captchaKey"`
}

type MeResp struct {
	UserId   int64    `json:"userId"`
	Username string   `json:"username"`
	Nickname string   `json:"nickname"`
	Avatar   string   `json:"avatar"`
	Roles    []string `json:"roles,omitempty"`
	Perms    []string `json:"perms,omitempty"`
}

type OptionItem struct {
	Label    string        `json:"label"`
	Value    int64         `json:"value"`
	Children []*OptionItem `json:"children,omitempty"`
}

type OrderGetReq struct {
	Id int64 `path:"id"`
}

type OrderInfo struct {
	Id               int64   `json:"id"`
	ShopId           int64   `json:"shop_id"`           // 店铺ID
	UserId           int64   `json:"user_id"`           // 用户ID
	OrderNo          string  `json:"order_no"`          // 订单号
	GoodsNumber      int64   `json:"goods_number"`      // 商品总数
	PayAmount        float64 `json:"pay_amount"`        // 订单金额(商品价格+配送费-优惠金额)
	GoodsAmount      float64 `json:"goods_amount"`      // 商品费用
	FreightAmount    float64 `json:"freight_amount"`    // 运费
	CouponAmount     float64 `json:"coupon_amount"`     // 优惠金费
	CouponId         int64   `json:"coupon_id"`         // 用户优惠券id
	ReceiverType     int64   `json:"receiver_type"`     // 地址类型0 配送 1自提点
	ReceiverName     string  `json:"receiver_name"`     // 收货人姓名
	ReceiverMobile   string  `json:"receiver_mobile"`   // 收货人电话
	ReceiverAddress  string  `json:"receiver_address"`  // 收货人地址
	DistributionId   int64   `json:"distribution_id"`   // 自提点ID
	DistributionInfo string  `json:"distribution_info"` // 自提点ID详情
	Remarks          string  `json:"remarks"`           // 备注
	PayTime          int64   `json:"pay_time"`          // 支付时间
	TradeNo          string  `json:"trade_no"`          // 支付单号
	Status           int64   `json:"status"`            // 订单状态  -2退款 -1=已关闭/0待支付/1已支付/2已发货/5待取货/10完成
	AppraiseStatus   int64   `json:"appraise_status"`   // 评价状态：0.待评价；1.已平价;
	CreatedAt        string  `json:"created_at"`
}

type OrderListReq struct {
	Keywords string `form:"keywords,omitempty,optional"`
	Status   int64  `form:"status,default=-1"`
	PageNum  int64  `form:"pageNum,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
}

type OrderListRsqp struct {
	List  []*OrderInfo `json:"list"`
	Total int64        `json:"total"`
}

type PmsBrand struct {
	Id        int64  `json:"id"`     // 主键
	ShopId    int64  `json:"shopId"` // shopID
	Name      string `json:"name"`   // 品牌名称
	Logo      string `json:"logo"`   // LOGO图片
	Sort      int64  `json:"sort"`   // 排序
	CreatedAt string `json:"createdAt"`
}

type PmsCategory struct {
	Id        int64          `json:"id"`
	ShopId    int64          `json:"shopId"`
	ParentId  int64          `json:"parentId"`
	Name      string         `json:"name"`
	Icon      string         `json:"icon"`
	Sort      int64          `json:"sort"`
	Visible   int64          `json:"visible"`
	CreatedAt string         `json:"createdAt"`
	Children  []*PmsCategory `json:"children,omitempty"`
}

type PmsCategoryAttribute struct {
	Id         int64  `json:"id"`         // 主键
	CategoryId int64  `json:"categoryId"` // 分类ID
	Name       string `json:"name"`       // 属性名称
	Type       int64  `json:"type"`       // 类型(1:规格;2:属性;)
	CreatedAt  string `json:"createdAt"`  // 创建时间
}

type PmsCategoryAttributeForm struct {
	CategoryId int64    `json:"categoryId"` // 分类ID
	Attributes []string `json:"attributes"` // 属性名称
	Type       int64    `json:"type"`       // 类型(1:规格;2:属性;)
}

type PmsCategoryAttributeListReq struct {
	CategoryId int64 `form:"categoryId"` // 分类ID
	Type       int64 `form:"type"`       // 类型(1:规格;2:属性;)
}

type PmsCategoryForm struct {
	Id       int64  `json:"id"`
	ShopId   int64  `json:"shopId"`
	ParentId int64  `json:"parentId"`
	Name     string `json:"name"`
	Icon     string `json:"icon"`
	Sort     int64  `json:"sort"`
	Visible  int64  `json:"visible"`
}

type PmsCategoryListReq struct {
	Status   int64  `form:"status,default=-1"`
	Keywords string `form:"keywords,omitempty,optional"`
	ShopId   int64  `form:"shopId,default=1"` // shopID
	PageNum  int64  `form:"pageNum,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
}

type PmsCategoryListResp struct {
	List []*PmsCategory `json:"list"`
}

type PmsGoods struct {
	Id           int64               `json:"id"`          // 主键
	ShopId       int64               `json:"shopId"`      // shopID
	CategoryId   int64               `json:"categoryId"`  // 商品类型ID
	BrandId      int64               `json:"brandId"`     // 商品品牌ID
	Name         string              `json:"name"`        // 商品名称
	OriginPrice  int64               `json:"originPrice"` // 原价【起】
	Price        int64               `json:"price"`       // 现价【起】
	Sales        int64               `json:"sales"`       // 销量
	PicUrl       string              `json:"picUrl"`      // 商品主图
	SubPicUrls   []string            `json:"subPicUrls"`  // 商品图册
	Unit         string              `json:"unit"`        // 单位
	Description  string              `json:"description"` // 商品简介
	Detail       string              `json:"detail"`      // 商品详情
	Status       int64               `json:"status"`      // 商品状态(0:下架 1:上架)
	BrandName    string              `json:"brandName,omitempty,optional"`
	CategoryName string              `json:"categoryName,omitempty,optional"`
	SkuList      []PmsSku            `json:"skuList,omitempty,optional"`
	AttrList     []PmsGoodsAttribute `json:"attrList,omitempty,optional"`
	SpecList     []PmsGoodsAttribute `json:"specList,omitempty,optional"`
	CreatedAt    string              `json:"createdAt"`
}

type PmsGoodsAttribute struct {
	Id          int64  `json:"id"`          // 主键
	GoodsId     int64  `json:"goodsId"`     // goods ID
	AttributeId int64  `json:"attributeId"` // 属性ID
	Name        string `json:"name"`        // 属性名称
	Value       string `json:"value"`       // 属性值
	Type        int64  `json:"type"`        // 类型(1:规格;2:属性;)
	PicUrl      string `json:"picUrl"`      // 规格图片
	CreatedAt   string `json:"createdAt"`
}

type PmsGoodsFormAttribute struct {
	Id      int64  `json:"id,optional,default=0"` // 主键
	GoodsId int64  `json:"goodsId,optional"`
	IdStr   string `json:"idStr,optional"`
	Name    string `json:"name"`
	Value   string `json:"value"`
	Type    int64  `json:"type,optional"`
	PicUrl  string `json:"picUrl,optional"`
}

type PmsGoodsFormSku struct {
	Id          int64  `json:"id,optional"`
	SkuSn       string `json:"skuSn"`                // 商品编码
	Name        string `json:"name"`                 // 商品名称
	SpecIds     string `json:"specIds"`              // 商品规格值，以英文逗号(,)分割
	Price       int64  `json:"price,optional"`       // 商品价格(单位：分)
	Stock       int64  `json:"stock,optional"`       // 库存数量
	LockedStock int64  `json:"lockedStock,optional"` // 库存锁定数量
	PicUrl      string `json:"picUrl,optional"`      // 商品图片地址
}

type PmsGoodsListReq struct {
	ShopId     int64  `form:"shopId,default=-1"`
	Keywords   string `form:"keywords,omitempty,optional"`
	Status     int64  `form:"status,default=-1"`
	PageNum    int64  `form:"pageNum,default=1"`
	PageSize   int64  `form:"pageSize,default=10"`
	CategoryId int64  `form:"categoryId,omitempty,optional"`
}

type PmsGoodsListRsqp struct {
	List  []PmsGoods `json:"list"`
	Total int64      `json:"total"`
}

type PmsSku struct {
	Id          int64  `json:"id"`
	GoodsId     int64  `json:"goodsId"`     // goods ID
	SkuSn       string `json:"skuSn"`       // 商品编码
	Name        string `json:"name"`        // 商品名称
	SpecIds     string `json:"specIds"`     // 商品规格值，以英文逗号(,)分割
	Price       int64  `json:"price"`       // 商品价格(单位：分)
	Stock       int64  `json:"stock"`       // 库存数量
	LockedStock int64  `json:"lockedStock"` // 库存锁定数量
	PicUrl      string `json:"picUrl"`      // 商品图片地址
	CreatedAt   string `json:"createdAt"`
}

type RouteData struct {
	Id          int64         `json:"id"`
	Path        string        `json:"path,omitempty"`
	Component   string        `json:"component,optional"`
	Name        string        `json:"name"`
	Meta        RouteMetaData `json:"meta"`
	Redirect    string        `json:"redirect,omitempty"`
	HasChildren bool          `json:"hasChildren,default=false"`
	Children    []*RouteData  `json:"children,omitempty"`
}

type RouteMetaData struct {
	Title     string   `json:"title"`
	Icon      string   `json:"icon,omitempty"`
	Roles     []string `json:"roles,omitempty"`
	Hidden    bool     `json:"hidden,default=false"`
	KeepAlive bool     `json:"keepAlive,default=true"`
}

type Shop struct {
	Id              int64   `json:"id"`
	Name            string  `json:"name"`
	Tel             string  `json:"tel"`
	Notice          string  `json:"notice"`
	DistributionFee float64 `json:"distributionFee"`
	Status          int64   `json:"status"`
	CreatedAt       string  `json:"createdAt"`
}

type ShopAddResp struct {
	Id int64 `json:"id"`
}

type ShopDelReq struct {
	Ids string `path:"ids"`
}

type ShopForm struct {
	Id              int64   `json:"id"`
	Name            string  `json:"name"`
	Tel             string  `json:"tel"`
	Notice          string  `json:"notice"`
	DistributionFee float64 `json:"distributionFee"`
}

type ShopGetReq struct {
	Id int64 `path:"id"`
}

type ShopListReq struct {
	Keywords string `form:"keywords,omitempty,optional"`
	Status   int64  `form:"status,default=-1"`
	PageNum  int64  `form:"pageNum,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
}

type ShopListResp struct {
	List  []*Shop `json:"list"`
	Total int64   `json:"total"`
}

type SysDeptAddResp struct {
	Id int64 `json:"id"`
}

type SysDeptDelReq struct {
	Ids string `path:"ids"`
}

type SysDeptFormReq struct {
	Id       int64  `json:"id,optional"`
	Name     string `json:"name"`
	ParentId int64  `json:"parent_id"`
	TreePath string `json:"tree_path"`
	Sort     int64  `json:"sort"`
	Status   int64  `json:"status"`
	CreateBy int64  `json:"create_by"`
	UpdateBy int64  `json:"update_by"`
}

type SysDeptGetReq struct {
	Id int64 `path:"id"`
}

type SysDeptInfo struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	ParentId  int64  `json:"parent_id"`
	TreePath  string `json:"tree_path"`
	Sort      int64  `json:"sort"`
	Status    int64  `json:"status"`
	CreateBy  int64  `json:"create_by"`
	UpdateBy  int64  `json:"update_by"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type SysDeptItem struct {
	Id       int64          `json:"id"`
	Name     string         `json:"name"`
	ParentId int64          `json:"parent_id"`
	TreePath string         `json:"tree_path"`
	Sort     int64          `json:"sort"`
	Status   int64          `json:"status"`
	CreateBy int64          `json:"create_by"`
	UpdateBy int64          `json:"update_by"`
	Children []*SysDeptItem `json:"children,omitempty"`
}

type SysDeptListReq struct {
	Keywords string `json:"keywords,omitempty,optional"`
	Status   int64  `json:"status,omitempty,optional,default=-1"`
}

type SysDeptOption struct {
	Label    string           `json:"label"`
	Value    int64            `json:"value"`
	Children []*SysDeptOption `json:"children,omitempty"`
}

type SysDictAddResp struct {
	Id int64 `json:"id"`
}

type SysDictDelReq struct {
	Ids string `path:"ids"`
}

type SysDictForm struct {
	Id        int64  `json:"id,optional"`
	TypeCode  string `json:"type_code"`
	Name      string `json:"name"`
	Value     string `json:"value"`
	Sort      int64  `json:"sort"`
	Status    int64  `json:"status"`
	Defaulted int64  `json:"defaulted,default=1"`
	Remark    string `json:"remark,optional"`
}

type SysDictGetReq struct {
	Id int64 `path:"id"`
}

type SysDictItem struct {
	Id        int64  `json:"id"`
	TypeCode  string `json:"type_code"`
	Name      string `json:"name"`
	Value     string `json:"value"`
	Sort      int64  `json:"sort,default=1"`
	Status    int64  `json:"status"`
	Defaulted int64  `json:"defaulted,default=1"`
	Remark    string `json:"remark,optional"`
	CreatedAt string `json:"created_at,optional"`
	UpdatedAt string `json:"updated_at,optional"`
}

type SysDictListReq struct {
	TypeCode string `form:"typeCode"`
	PageNum  int64  `form:"pageNum,omitempty,optional,default=1"`
	PageSize int64  `form:"pageSize,omitempty,optional,default=10"`
}

type SysDictListResp struct {
	List  []*SysDictItem `json:"list"`
	Total int64          `json:"total"`
}

type SysDictOption struct {
	Label    string          `json:"label"`
	Value    string          `json:"value"`
	Children []SysDictOption `json:"children,omitempty"`
}

type SysDictTypeAddResp struct {
	Id int64 `json:"id"`
}

type SysDictTypeDelReq struct {
	Ids string `path:"ids"`
}

type SysDictTypeForm struct {
	Id     int64  `json:"id,optional"`
	Name   string `json:"name"`
	Code   string `json:"code"`
	Status int64  `json:"status"`
	Remark string `json:"remark,optional"`
}

type SysDictTypeGetReq struct {
	Id int64 `path:"id"`
}

type SysDictTypeItem struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Status    int64  `json:"status"`
	Remark    string `json:"remark,optional"`
	CreatedAt string `json:"created_at,optional"`
	UpdatedAt string `json:"updated_at,optional"`
}

type SysDictTypeListReq struct {
	Keywords string `form:"keywords,omitempty,optional"`
	PageNum  int64  `form:"pageNum,omitempty,optional,default=1"`
	PageSize int64  `form:"pageSize,omitempty,optional,default=10"`
}

type SysDictTypeListResp struct {
	List  []*SysDictTypeItem `json:"list"`
	Total int64              `json:"total"`
}

type SysMenuAddResp struct {
	Id int64 `json:"id"`
}

type SysMenuChangeVisibleReq struct {
	MenuId  int64 `json:"menuId"`
	Visible int64 `json:"visible"`
}

type SysMenuDelReq struct {
	Ids string `path:"ids"`
}

type SysMenuForm struct {
	Id        int64  `json:"id,optional"`
	ParentId  int64  `json:"parentId"`
	Name      string `json:"name"`
	Type      int64  `json:"type,optional"`
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Perm      string `json:"perm,optional"`
	Visible   int64  `json:"visible,optional"`
	Sort      int64  `json:"sort,default=false"`
	Icon      string `json:"icon,optional"`
	Redirect  string `json:"redirect,optional"`
}

type SysMenuGetReq struct {
	Id int64 `path:"id"`
}

type SysMenuIdsResp struct {
	Items []int64 `json:"items"`
}

type SysMenuInfo struct {
	Id        int64  `json:"id"`
	ParentId  int64  `json:"parentId"`
	TreePath  string `json:"treePath"`
	Name      string `json:"name"`
	Type      int64  `json:"type"`
	Path      string `json:"path"`
	Component string `json:"component"`
	Perm      string `json:"perm"`
	Visible   int64  `json:"visible"`
	Sort      int64  `json:"sort,default=1"`
	Icon      string `json:"icon"`
	Redirect  string `json:"redirect"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type SysMenuItem struct {
	Id        int64          `json:"id"`
	ParentId  int64          `json:"parent_id"`
	TreePath  string         `json:"tree_path"`
	Name      string         `json:"name"`
	Type      int64          `json:"type"`
	Path      string         `json:"path"`
	Component string         `json:"component"`
	Perm      string         `json:"perm"`
	Visible   int64          `json:"visible"`
	Sort      int64          `json:"sort"`
	Icon      string         `json:"icon"`
	Redirect  string         `json:"redirect"`
	Children  []*SysMenuItem `json:"children,omitempty"`
}

type SysMenuListReq struct {
	Keywords string `json:"keywords,omitempty,optional"`
}

type SysMenuOption struct {
	Label    string          `json:"label"`
	Value    int64           `json:"value"`
	Children []SysMenuOption `json:"children,omitempty"`
}

type SysRoleAddResp struct {
	Id int64 `json:"id"`
}

type SysRoleChangeStatusReq struct {
	RoleId int64  `json:"roleId"`
	Status string `json:"status"`
}

type SysRoleDelReq struct {
	Ids string `path:"ids"`
}

type SysRoleFormReq struct {
	Id        int64  `json:"id,optional"`
	Name      string `json:"name"`      // 角色名称
	Code      string `json:"code"`      // 角色编码
	Sort      int64  `json:"sort"`      // 显示顺序
	Status    int64  `json:"status"`    // 角色状态(1-正常；0-停用)
	DataScope int64  `json:"dataScope"` // 数据权限(0-所有数据；1-部门及子部门数据；2-本部门数据；3-本人数据)
}

type SysRoleGetReq struct {
	Id int64 `path:"id"`
}

type SysRoleInfo struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Sort      int64  `json:"sort"`
	Status    int64  `json:"status"`
	DataScope int64  `json:"dataScope"`
}

type SysRoleListReq struct {
	Keywords string `form:"keywords,omitempty,optional"`
	PageNum  int64  `form:"pageNum,omitempty,optional,default=1"`
	PageSize int64  `form:"pageSize,omitempty,optional,default=10"`
}

type SysRoleListResp struct {
	List  []*SysRoleInfo `json:"list"`
	Total int64          `json:"total"`
}

type SysRoleMenuIdsReq struct {
	Id int64 `path:"id"`
}

type SysRoleOption struct {
	Label string `json:"label"`
	Value int64  `json:"value"`
}

type SysSetMenuIdsReq struct {
	RoleId  int64   `json:"roleId,optional"`
	MenuIds []int64 `json:"menuIds,optional"`
}

type SysTypeReq struct {
	TypeCode string `path:"typeCode"`
}

type SysUserAddResp struct {
	Id int64 `json:"id"`
}

type SysUserChangePwdReq struct {
	UserId   int64  `json:"userId"`
	Password string `json:"password"`
}

type SysUserChangeStatusReq struct {
	UserId int64  `json:"userId"`
	Status string `json:"status"`
}

type SysUserDelReq struct {
	Ids string `path:"ids"`
}

type SysUserFormReq struct {
	Id       int64   `json:"id,optional"`
	Username string  `json:"username"`
	Nickname string  `json:"nickname,optional"`
	Gender   int64   `json:"gender,optional"`
	Password string  `json:"password,optional"`
	DeptId   int64   `json:"deptId,optional"`
	Avatar   string  `json:"avatar,optional"`
	Mobile   string  `json:"mobile,optional"`
	Status   int64   `json:"status,default=1"`
	Email    string  `json:"email,optional"`
	RoleIds  []int64 `json:"roleIds"`
}

type SysUserGet struct {
	Id       int64   `json:"id"`
	Username string  `json:"username"` // 用户名
	Nickname string  `json:"nickname"` // 昵称
	Gender   int64   `json:"gender"`   // 性别((1:男;2:女))
	DeptId   int64   `json:"deptId"`   // 部门ID
	Avatar   string  `json:"avatar"`   // 用户头像
	Mobile   string  `json:"mobile"`   // 联系方式
	Status   int64   `json:"status"`   // 用户状态((1:正常;0:禁用))
	Email    string  `json:"email"`    // 用户邮箱
	RoleIds  []int64 `json:"roleIds"`
}

type SysUserGetReq struct {
	Id int64 `path:"id"`
}

type SysUserInfo struct {
	Id          int64    `json:"id"`
	Username    string   `json:"username"` // 用户名
	Nickname    string   `json:"nickname"` // 昵称
	Gender      int64    `json:"gender"`   // 性别((1:男;2:女))
	Password    string   `json:"password"` // 密码
	DeptId      int64    `json:"dept_id"`  // 部门ID
	Avatar      string   `json:"avatar"`   // 用户头像
	Mobile      string   `json:"mobile"`   // 联系方式
	Status      int64    `json:"status"`   // 用户状态((1:正常;0:禁用))
	Email       string   `json:"email"`    // 用户邮箱
	Roles       []string `json:"roles"`
	DeptName    string   `json:"deptName"`
	GenderLabel string   `json:"genderLabel"` // 性别((1:男;2:女))
	CreatedAt   string   `json:"created_at"`  // 创建时间
	UpdatedAt   string   `json:"updated_at"`  // 更新时间
}

type SysUserListReq struct {
	Keywords  string `form:"keywords,omitempty,optional"`
	DeptId    int64  `form:"deptId,omitempty,optional"`
	Status    int64  `form:"status,omitempty,optional,default=-1"`
	PageNum   int64  `form:"pageNum,omitempty,optional,default=1"`
	PageSize  int64  `form:"pageSize,omitempty,optional,default=10"`
	StartTime string `form:"startTime,optional"` // 开始时间
	EndTime   string `form:"endTime,optional"`   // 结束时间
}

type SysUserListResp struct {
	List  []*SysUserInfo `json:"list"`
	Total int64          `json:"total"`
}

type TokenResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UmsUserAddResp struct {
	Id int64 `json:"id"`
}

type UmsUserDelReq struct {
	Ids string `path:"ids"`
}

type UmsUserGetReq struct {
	Id int64 `path:"id"`
}

type UmsUserListReq struct {
	Keywords string `form:"keywords,omitempty,optional"`
	Status   int64  `form:"status,default=-1"`
	PageNum  int64  `form:"pageNum,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
}

type UmsUserThirdlistReq struct {
	Keywords string `form:"keywords,omitempty,optional"`
	Status   int64  `form:"status,default=-1"`
	PageNum  int64  `form:"pageNum,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
}

type UserAddress struct {
	ID        int64  `json:"id"`        // ID
	ShopID    int64  `json:"shopId"`    // 店铺id
	UiD       int64  `json:"uid"`       // 用户ID
	Name      string `json:"name"`      // 联系人
	Mobile    string `json:"mobile"`    // 手机号
	Area      string `json:"area"`      // 学校地址
	Info      string `json:"info"`      // 详细地址
	IsDefault int8   `json:"isDefault"` // 是否默认
}

type UserForm struct {
	Id        int64  `json:"id,optional"`
	Mobile    string `json:"mobile,optional"`   //电话号码
	Username  string `json:"username,optional"` //姓名
	Nickname  string `json:"nickname,optional"` //昵称
	Avatar    string `json:"avatar,optional"`   //头像
	IdCard    string `json:"idCard,optional"`   //身份证号码
	Gender    int64  `json:"gender,optional"`   //性别 0 未知 1男 2女
	Signature string `json:"signature,optional"`
	Birthday  string `json:"birthday,,default=0000:01:01"`
	Tags      string `json:"tags,optional"`
	Source    string `json:"source,optional"`
	SourceUid int64  `json:"sourceUid,optional"`
}

type UserInfo struct {
	Id        int64          `json:"id"`
	Mobile    string         `json:"mobile"` //电话号码
	Username  string         `json:"username,optional"`
	Nickname  string         `json:"nickname"`        //昵称
	Avatar    string         `json:"avatar"`          //头像
	IdCard    string         `json:"idCard"`          //身份证号码
	Gender    int8           `json:"gender,optional"` //性别 0 未知 1男 2女
	Signature string         `json:"signature"`       //签名
	Birthday  string         `json:"birthday"`        //生日
	Tags      string         `json:"tags"`            //tags
	Source    string         `json:"source"`          //来源，APP H5
	SourceUid int64          `json:"sourceUid"`       //邀请uid
	CreatedAt string         `json:"created_at"`
	Addresses []*UserAddress `json:"addresses"`
}

type UserListRsqp struct {
	List  []*UserInfo `json:"list"`
	Total int64       `json:"total"`
}

type UserThird struct {
	Id        int64  `json:"id"`       // id
	Uid       int64  `json:"uid"`      // 会员ID
	Platform  string `json:"platform"` // 第三方应用
	Openid    string `json:"openid"`   // 第三方唯一ID
	Unionid   string `json:"unionid"`  // 小程序unionid
	Nickname  string `json:"nickname"` // 第三方会员昵称
	Avatar    string `json:"avatar"`   // 第三方会员头像
	CreatedAt string `json:"createdAt"`
}

type UserThirdListRsqp struct {
	List  []*UserThird `json:"list"`
	Total int64        `json:"total"`
}
