// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type TokenResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type MeResp struct {
	UserId   int64    `json:"userId"`
	Username string   `json:"username"`
	Nickname string   `json:"nickname"`
	Avatar   string   `json:"avatar"`
	Roles    []string `json:"roles,omitempty"`
	Perms    []string `json:"perms,omitempty"`
}

type SysUserInfo struct {
	Id          int64    `json:"id"`
	Username    string   `json:"username"` // 用户名
	Nickname    string   `json:"nickname"` // 昵称
	Gender      int64    `json:"gender"`   // 性别((1:男;2:女))
	Password    string   `json:"password"` // 密码
	DeptId      int64    `json:"dept_id"`  // 部门ID
	Avatar      string   `json:"avatar"`   // 用户头像
	Mobile      string   `json:"mobile"`   // 联系方式
	Status      int64    `json:"status"`   // 用户状态((1:正常;0:禁用))
	Email       string   `json:"email"`    // 用户邮箱
	Roles       []string `json:"roles"`
	DeptName    string   `json:"deptName"`
	GenderLabel string   `json:"genderLabel"` // 性别((1:男;2:女))
	CreatedAt   string   `json:"created_at"`  // 创建时间
	UpdatedAt   string   `json:"updated_at"`  // 更新时间
}

type SysUserGet struct {
	Id       int64   `json:"id"`
	Username string  `json:"username"` // 用户名
	Nickname string  `json:"nickname"` // 昵称
	Gender   int64   `json:"gender"`   // 性别((1:男;2:女))
	DeptId   int64   `json:"deptId"`   // 部门ID
	Avatar   string  `json:"avatar"`   // 用户头像
	Mobile   string  `json:"mobile"`   // 联系方式
	Status   int64   `json:"status"`   // 用户状态((1:正常;0:禁用))
	Email    string  `json:"email"`    // 用户邮箱
	RoleIds  []int64 `json:"roleIds"`
}

type SysUserListReq struct {
	Keywords  string `form:"keywords,omitempty,optional"`
	DeptId    int64  `form:"deptId,omitempty,optional"`
	Status    int64  `form:"status,omitempty,optional,default=-1"`
	PageNum   int64  `form:"pageNum,omitempty,optional,default=1"`
	PageSize  int64  `form:"pageSize,omitempty,optional,default=10"`
	StartTime string `form:"startTime,optional"` // 开始时间
	EndTime   string `form:"endTime,optional"`   // 结束时间
}

type SysUserListResp struct {
	List  []*SysUserInfo `json:"list"`
	Total int64          `json:"total"`
}

type SysUserFormReq struct {
	Id       int64   `json:"id,optional"`
	Username string  `json:"username"`
	Nickname string  `json:"nickname,optional"`
	Gender   int64   `json:"gender,optional"`
	Password string  `json:"password,optional"`
	DeptId   int64   `json:"deptId,optional"`
	Avatar   string  `json:"avatar,optional"`
	Mobile   string  `json:"mobile,optional"`
	Status   int64   `json:"status,default=1"`
	Email    string  `json:"email,optional"`
	RoleIds  []int64 `json:"roleIds"`
}

type SysUserChangePwdReq struct {
	UserId   int64  `json:"userId"`
	Password string `json:"password"`
}

type SysUserChangeStatusReq struct {
	UserId int64  `json:"userId"`
	Status string `json:"status"`
}

type PathIdReq struct {
	Id int64 `path:"id"`
}

type PathIdsReq struct {
	Ids string `path:"ids"`
}

type IdReq struct {
	Id int64 `form:"id"`
}

type IdResp struct {
	ID int64 `json:"id"`
}

type ListReq struct {
	Keywords string `form:"keywords,omitempty,optional"`
	Status   int64  `form:"status,default=-1"`
	PageNum  int64  `form:"pageNum,default=1"`
	PageSize int64  `form:"pageSize,default=10"`
}

type OptionItem struct {
	Label    string        `json:"label"`
	Value    int64         `json:"value"`
	Children []*OptionItem `json:"children,omitempty"`
}

type OptionsResp struct {
	List []*OptionItem `json:"list"`
}

type RoutesResp struct {
	List []*RouteData `json:"list"`
}

type RouteMetaData struct {
	Title     string   `json:"title"`
	Icon      string   `json:"icon,omitempty"`
	Roles     []string `json:"roles,omitempty"`
	Hidden    bool     `json:"hidden,default=false"`
	KeepAlive bool     `json:"keepAlive,default=true"`
}

type RouteData struct {
	Id          int64         `json:"id"`
	Path        string        `json:"path,omitempty"`
	Component   string        `json:"component,optional"`
	Name        string        `json:"name"`
	Meta        RouteMetaData `json:"meta"`
	Redirect    string        `json:"redirect,omitempty"`
	HasChildren bool          `json:"hasChildren,default=false"`
	Children    []*RouteData  `json:"children,omitempty"`
}

type SysMenuInfo struct {
	Id        int64  `json:"id"`
	ParentId  int64  `json:"parentId"`
	TreePath  string `json:"treePath"`
	Name      string `json:"name"`
	Type      int64  `json:"type"`
	Path      string `json:"path"`
	Component string `json:"component"`
	Perm      string `json:"perm"`
	Visible   int64  `json:"visible"`
	Sort      int64  `json:"sort,default=1"`
	Icon      string `json:"icon"`
	Redirect  string `json:"redirect"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type SysMenuForm struct {
	Id        int64  `json:"id,optional"`
	ParentId  int64  `json:"parentId"`
	Name      string `json:"name"`
	Type      int64  `json:"type,optional"`
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Perm      string `json:"perm,optional"`
	Visible   int64  `json:"visible,optional"`
	Sort      int64  `json:"sort,default=false"`
	Icon      string `json:"icon,optional"`
	Redirect  string `json:"redirect,optional"`
}

type SysMenuListReq struct {
	Keywords string `json:"keywords,omitempty,optional"`
}

type SysMenuItem struct {
	Id        int64          `json:"id"`
	ParentId  int64          `json:"parent_id"`
	TreePath  string         `json:"tree_path"`
	Name      string         `json:"name"`
	Type      int64          `json:"type"`
	Path      string         `json:"path"`
	Component string         `json:"component"`
	Perm      string         `json:"perm"`
	Visible   int64          `json:"visible"`
	Sort      int64          `json:"sort"`
	Icon      string         `json:"icon"`
	Redirect  string         `json:"redirect"`
	Children  []*SysMenuItem `json:"children,omitempty"`
}

type SysMenuListResp struct {
	List []*SysMenuItem `json:"list"`
}

type SysMenuChangeVisibleReq struct {
	MenuId  int64 `json:"menuId"`
	Visible int64 `json:"visible"`
}

type SysMenuOption struct {
	Label    string           `json:"label"`
	Value    int64            `json:"value"`
	Children []*SysMenuOption `json:"children,omitempty"`
}

type SysMenuOptionsResp struct {
	List []*SysMenuOption `json:"list"`
}

type SysRoleInfo struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Sort      int64  `json:"sort"`
	Status    int64  `json:"status"`
	DataScope int64  `json:"dataScope"`
}

type SysRoleListReq struct {
	Keywords string `form:"keywords,omitempty,optional"`
	PageNum  int64  `form:"pageNum,omitempty,optional,default=1"`
	PageSize int64  `form:"pageSize,omitempty,optional,default=10"`
}

type SysRoleListResp struct {
	List  []*SysRoleInfo `json:"list"`
	Total int64          `json:"total"`
}

type SysRoleFormReq struct {
	Id        int64  `json:"id,optional"`
	Name      string `json:"name"`      // 角色名称
	Code      string `json:"code"`      // 角色编码
	Sort      int64  `json:"sort"`      // 显示顺序
	Status    int64  `json:"status"`    // 角色状态(1-正常；0-停用)
	DataScope int64  `json:"dataScope"` // 数据权限(0-所有数据；1-部门及子部门数据；2-本部门数据；3-本人数据)
}

type SysMenuIdsResp struct {
	Items []int64 `json:"items"`
}

type SysSetMenuIdsReq struct {
	RoleId  int64   `json:"roleId,optional"`
	MenuIds []int64 `json:"menuIds,optional"`
}

type SysRoleChangeStatusReq struct {
	RoleId int64  `json:"roleId"`
	Status string `json:"status"`
}

type SysRoleOption struct {
	Label string `json:"label"`
	Value int64  `json:"value"`
}

type SysRoleOptionsResp struct {
	List []*SysRoleOption `json:"list"`
}

type SysDeptInfo struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	ParentId  int64  `json:"parent_id"`
	TreePath  string `json:"tree_path"`
	Sort      int64  `json:"sort"`
	Status    int64  `json:"status"`
	CreateBy  int64  `json:"create_by"`
	UpdateBy  int64  `json:"update_by"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type SysDeptListReq struct {
	Keywords string `json:"keywords,omitempty,optional"`
	Status   int64  `json:"status,omitempty,optional,default=-1"`
}

type SysDeptItem struct {
	Id       int64          `json:"id"`
	Name     string         `json:"name"`
	ParentId int64          `json:"parent_id"`
	TreePath string         `json:"tree_path"`
	Sort     int64          `json:"sort"`
	Status   int64          `json:"status"`
	CreateBy int64          `json:"create_by"`
	UpdateBy int64          `json:"update_by"`
	Children []*SysDeptItem `json:"children,omitempty"`
}

type SysDeptListResp struct {
	List []*SysDeptItem `json:"list"`
}

type SysDeptFormReq struct {
	Id       int64  `json:"id,optional"`
	Name     string `json:"name"`
	ParentId int64  `json:"parent_id"`
	TreePath string `json:"tree_path"`
	Sort     int64  `json:"sort"`
	Status   int64  `json:"status"`
	CreateBy int64  `json:"create_by"`
	UpdateBy int64  `json:"update_by"`
}

type SysDeptOption struct {
	Label    string           `json:"label"`
	Value    int64            `json:"value"`
	Children []*SysDeptOption `json:"children,omitempty"`
}

type SysDeptOptionsResp struct {
	List []*SysDeptOption `json:"list"`
}

type SysDictTypeItem struct {
	Id        int64  `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Status    int64  `json:"status"`
	Remark    string `json:"remark,optional"`
	CreatedAt string `json:"created_at,optional"`
	UpdatedAt string `json:"updated_at,optional"`
}

type SysDictItem struct {
	Id        int64  `json:"id"`
	TypeCode  string `json:"type_code"`
	Name      string `json:"name"`
	Value     string `json:"value"`
	Sort      int64  `json:"sort,default=1"`
	Status    int64  `json:"status"`
	Defaulted int64  `json:"defaulted,default=1"`
	Remark    string `json:"remark,optional"`
	CreatedAt string `json:"created_at,optional"`
	UpdatedAt string `json:"updated_at,optional"`
}

type SysDictTypeForm struct {
	Id     int64  `json:"id,optional"`
	Name   string `json:"name"`
	Code   string `json:"code"`
	Status int64  `json:"status"`
	Remark string `json:"remark,optional"`
}

type SysDictForm struct {
	Id        int64  `json:"id,optional"`
	TypeCode  string `json:"type_code"`
	Name      string `json:"name"`
	Value     string `json:"value"`
	Sort      int64  `json:"sort"`
	Status    int64  `json:"status"`
	Defaulted int64  `json:"defaulted,default=1"`
	Remark    string `json:"remark,optional"`
}

type SysDictTypeListReq struct {
	Keywords string `form:"keywords,omitempty,optional"`
	PageNum  int64  `form:"pageNum,omitempty,optional,default=1"`
	PageSize int64  `form:"pageSize,omitempty,optional,default=10"`
}

type SysDictTypeListResp struct {
	List  []*SysDictTypeItem `json:"list"`
	Total int64              `json:"total"`
}

type SysDictListReq struct {
	TypeCode string `form:"typeCode"`
	PageNum  int64  `form:"pageNum,omitempty,optional,default=1"`
	PageSize int64  `form:"pageSize,omitempty,optional,default=10"`
}

type SysDictListResp struct {
	List  []*SysDictItem `json:"list"`
	Total int64          `json:"total"`
}

type SysTypeReq struct {
	TypeCode string `path:"typeCode"`
}

type SysDictOption struct {
	Label    string           `json:"label"`
	Value    string           `json:"value"`
	Children []*SysDictOption `json:"children,omitempty"`
}

type SysDictOptionsResp struct {
	List []*SysDictOption `json:"list"`
}

type UserForm struct {
	Id        int64  `json:"id,optional"`
	Mobile    string `json:"mobile,optional"`   //电话号码
	Username  string `json:"username,optional"` //姓名
	Nickname  string `json:"nickname,optional"` //昵称
	Avatar    string `json:"avatar,optional"`   //头像
	IdCard    string `json:"idCard,optional"`   //身份证号码
	Gender    int64  `json:"gender,optional"`   //性别 0 未知 1男 2女
	Signature string `json:"signature,optional"`
	Birthday  string `json:"birthday,optional"`
	Tags      string `json:"tags,optional"`
	Source    string `json:"source,optional"`
	SourceUid int64  `json:"sourceUid,optional"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Mobile    string `json:"mobile"` //电话号码
	Username  string `json:"username,optional"`
	Nickname  string `json:"nickname"`        //昵称
	Avatar    string `json:"avatar"`          //头像
	IdCard    string `json:"idCard"`          //身份证号码
	Gender    int8   `json:"gender,optional"` //性别 0 未知 1男 2女
	Signature string `json:"signature"`       //签名
	Birthday  string `json:"birthday"`        //生日
	Tags      string `json:"tags"`            //tags
	Source    string `json:"source"`          //来源，APP H5
	SourceUid int64  `json:"sourceUid"`       //邀请uid
	CreatedAt string `json:"created_at"`
}

type UserListRsqp struct {
	List  []*UserInfo `json:"list"`
	Total int64       `json:"total"`
}

type UserThird struct {
	Id        int64  `json:"id"`       // id
	Uid       int64  `json:"uid"`      // 会员ID
	Platform  string `json:"platform"` // 第三方应用
	Openid    string `json:"openid"`   // 第三方唯一ID
	Unionid   string `json:"unionid"`  // 小程序unionid
	Nickname  string `json:"nickname"` // 第三方会员昵称
	Avatar    string `json:"avatar"`   // 第三方会员头像
	CreatedAt string `json:"created_at"`
}

type UserThirdListRsqp struct {
	List  []*UserThird `json:"list"`
	Total int64        `json:"total"`
}

type FileUpload struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}
