dbType: mysql
host: 192.168.3.88
port: 13306
user: root
password: 123456
schema: mall-boot
tables:
  - sys_log
  - sys_notice
serviceName: boot
outFile: ./data/api/boot.api
jwt: true
middleware:
  - Auth
ignoreColumns: 
  - deleted_at 
  - version
  - mid
onlySearch:
  - id
  - created_at
  - updated_at
  - deleted_at