// Code generated by goctl. DO NOT EDIT.
// Source: ums.proto

package ums

import (
	"context"

	"fast-boot/app/rpc/ums/umsPb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BindReq             = umsPb.BindReq
	IdReq               = umsPb.IdReq
	IdResp              = umsPb.IdResp
	IdsReq              = umsPb.IdsReq
	ListReq             = umsPb.ListReq
	OpenIdReq           = umsPb.OpenIdReq
	SuccessIdResp       = umsPb.SuccessIdResp
	SuccessResp         = umsPb.SuccessResp
	User                = umsPb.User
	UserAddress         = umsPb.UserAddress
	UserAddressListResp = umsPb.UserAddressListResp
	UserCarts           = umsPb.UserCarts
	UserFeedback        = umsPb.UserFeedback
	UserForm            = umsPb.UserForm
	UserInfoResp        = umsPb.UserInfoResp
	UserListResp        = umsPb.UserListResp
	UserThird           = umsPb.UserThird
	UserThirdListResp   = umsPb.UserThirdListResp

	Ums interface {
		// UserUpdate
		ByOpenId(ctx context.Context, in *OpenIdReq, opts ...grpc.CallOption) (*UserInfoResp, error)
		Bind(ctx context.Context, in *BindReq, opts ...grpc.CallOption) (*UserInfoResp, error)
		// -------
		UserGet(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*User, error)
		UserList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error)
		UserAdd(ctx context.Context, in *UserForm, opts ...grpc.CallOption) (*SuccessIdResp, error)
		UserUpdate(ctx context.Context, in *UserForm, opts ...grpc.CallOption) (*SuccessResp, error)
		UserDel(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*SuccessResp, error)
		// third
		UserThirdList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserThirdListResp, error)
	}

	defaultUms struct {
		cli zrpc.Client
	}
)

func NewUms(cli zrpc.Client) Ums {
	return &defaultUms{
		cli: cli,
	}
}

// UserUpdate
func (m *defaultUms) ByOpenId(ctx context.Context, in *OpenIdReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := umsPb.NewUmsClient(m.cli.Conn())
	return client.ByOpenId(ctx, in, opts...)
}

func (m *defaultUms) Bind(ctx context.Context, in *BindReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := umsPb.NewUmsClient(m.cli.Conn())
	return client.Bind(ctx, in, opts...)
}

// -------
func (m *defaultUms) UserGet(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*User, error) {
	client := umsPb.NewUmsClient(m.cli.Conn())
	return client.UserGet(ctx, in, opts...)
}

func (m *defaultUms) UserList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := umsPb.NewUmsClient(m.cli.Conn())
	return client.UserList(ctx, in, opts...)
}

func (m *defaultUms) UserAdd(ctx context.Context, in *UserForm, opts ...grpc.CallOption) (*SuccessIdResp, error) {
	client := umsPb.NewUmsClient(m.cli.Conn())
	return client.UserAdd(ctx, in, opts...)
}

func (m *defaultUms) UserUpdate(ctx context.Context, in *UserForm, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := umsPb.NewUmsClient(m.cli.Conn())
	return client.UserUpdate(ctx, in, opts...)
}

func (m *defaultUms) UserDel(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	client := umsPb.NewUmsClient(m.cli.Conn())
	return client.UserDel(ctx, in, opts...)
}

// third
func (m *defaultUms) UserThirdList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserThirdListResp, error) {
	client := umsPb.NewUmsClient(m.cli.Conn())
	return client.UserThirdList(ctx, in, opts...)
}
