// Code generated by goctl. DO NOT EDIT.
// Source: ums.proto

package server

import (
	"context"

	"fast-boot/app/rpc/ums/internal/logic"
	"fast-boot/app/rpc/ums/internal/svc"
	"fast-boot/app/rpc/ums/umsPb"
)

type UmsServer struct {
	svcCtx *svc.ServiceContext
	umsPb.UnimplementedUmsServer
}

func NewUmsServer(svcCtx *svc.ServiceContext) *UmsServer {
	return &UmsServer{
		svcCtx: svcCtx,
	}
}

// UserUpdate
func (s *UmsServer) ByOpenId(ctx context.Context, in *umsPb.OpenIdReq) (*umsPb.UserInfoResp, error) {
	l := logic.NewByOpenIdLogic(ctx, s.svcCtx)
	return l.ByOpenId(in)
}

func (s *UmsServer) Bind(ctx context.Context, in *umsPb.BindReq) (*umsPb.UserInfoResp, error) {
	l := logic.NewBindLogic(ctx, s.svcCtx)
	return l.Bind(in)
}

// -------
func (s *UmsServer) UserGet(ctx context.Context, in *umsPb.IdReq) (*umsPb.User, error) {
	l := logic.NewUserGetLogic(ctx, s.svcCtx)
	return l.UserGet(in)
}

func (s *UmsServer) UserList(ctx context.Context, in *umsPb.ListReq) (*umsPb.UserListResp, error) {
	l := logic.NewUserListLogic(ctx, s.svcCtx)
	return l.UserList(in)
}

func (s *UmsServer) UserAdd(ctx context.Context, in *umsPb.UserForm) (*umsPb.SuccessIdResp, error) {
	l := logic.NewUserAddLogic(ctx, s.svcCtx)
	return l.UserAdd(in)
}

func (s *UmsServer) UserUpdate(ctx context.Context, in *umsPb.UserForm) (*umsPb.SuccessResp, error) {
	l := logic.NewUserUpdateLogic(ctx, s.svcCtx)
	return l.UserUpdate(in)
}

func (s *UmsServer) UserDel(ctx context.Context, in *umsPb.IdsReq) (*umsPb.SuccessResp, error) {
	l := logic.NewUserDelLogic(ctx, s.svcCtx)
	return l.UserDel(in)
}

// third
func (s *UmsServer) UserThirdList(ctx context.Context, in *umsPb.ListReq) (*umsPb.UserThirdListResp, error) {
	l := logic.NewUserThirdListLogic(ctx, s.svcCtx)
	return l.UserThirdList(in)
}
