// Code generated by goctl. DO NOT EDIT.
package types

type AuthCodeReq struct {
	Code string `json:"code"`
}

type DecryptReq struct {
	OpenId        string `json:"openId"`
	EncryptedData string `json:"encryptedData"`
	Iv            string `json:"iv"`
}

type MobileResp struct {
	PhoneNumber     string `json:"phoneNumber"`
	PurePhoneNumber string `json:"purePhoneNumber"`
}

type BindReq struct {
	OpenId        string `json:"openId"`
	EncryptedData string `json:"encryptedData"`
	Iv            string `json:"iv"`
}

type TokenResp struct {
	OpenID string `json:"openID"`
	Token  string `json:"token"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Mobile    string `json:"mobile"`    //电话号码
	Name      string `json:"name"`      //姓名
	Nickname  string `json:"nickname"`  //昵称
	Avatar    string `json:"avatar"`    //头像
	IdCard    string `json:"idCard"`    //身份证号码
	Sex       int64  `json:"sex"`       //性别 0 未知 1男 2女
	Signature string `json:"signature"` //签名
	Birthday  string `json:"birthday"`  //生日
	Tags      string `json:"tags"`      //tags
	Source    string `json:"source"`    //来源，APP H5
	SourceUid int64  `json:"sourceUid"` //邀请uid
}

type SendSmsReq struct {
}

type SendSmsResp struct {
}

type WxPayCallBackReq struct {
}

type WxPayCallBackResp struct {
	ReturnCode string `json:"return_code"`
}

type FileUploadResp struct {
	Hash string `json:"hash"`
	Name string `json:"name"`
	Ext  string `json:"ext"`
	Size int64  `json:"size"`
	Path string `json:"path"`
}
