dbType: mysql
host: localhost
port: 3306
user: root
password: 123456
schema: mall-boot
tables:
  - name: user_address
onlyModel: true
outPath: ./data/model/
outFile:
withUnitTest: false
modelPkgName: model
fieldNullable: false
fieldWithIndexTag: false
fieldWithTypeTag: false
fieldCoverable: false
 