dbType: mysql
host: 192.168.3.88
port: 13306
user: root
password: 123456
schema: mall-boot
tables:
  - name: sys_log
  - name: sys_notice
onlyModel: true
outPath: ./data/model/
outFile:
withUnitTest: false
modelPkgName: model
fieldNullable: false
fieldWithIndexTag: false
fieldWithTypeTag: false
fieldCoverable: false
 