dbType: mysql
host: 192.168.3.88
port: 13306
user: root
password: 123456
schema: mall-boot
tables:
  - sys_log
  - sys_notice
serviceName: sys
packageName: sys
goPackageName: ./sys
outFile: ./data/pd/sys.proto
ignoreTables:  
ignoreColumns: 
  - deleted_at 
  - version
onlySearch:
  - id
  - created_at
  - updated_at

