// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "fast-boot/app/api/wxapp/internal/handler/auth"
	callBack "fast-boot/app/api/wxapp/internal/handler/callBack"
	other "fast-boot/app/api/wxapp/internal/handler/other"
	"fast-boot/app/api/wxapp/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/code",
				Handler: auth.CodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/getMobile",
				Handler: auth.GetMobileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/bind",
				Handler: auth.BindHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/me",
				Handler: auth.MeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/SendSms",
				Handler: other.SendSmsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: other.FileUploadHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/callBack/wxPay",
				Handler: callBack.WxPayHandler(serverCtx),
			},
		},
	)
}
