// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "fast-boot/app/api/test/internal/handler/auth"
	"fast-boot/app/api/test/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reg",
				Handler: auth.RegHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/test",
				Handler: auth.TestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/me",
				Handler: auth.MeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/auth"),
	)
}
