Name: pms.rpc
ListenOn: 0.0.0.0:7003
Etcd:
  Hosts:
    - 192.168.3.88:12379
  Key: pms.rpc

GormConf:
  SqlType: 1
  IsOpenReadDb: false   # 是否开启读写分离配置（true=开启、false=关闭），IsOpenReadDb=开启,Read 部分参数有效，否则Read部分参数直接忽略
  SlowThreshold: 30     # 慢 SQL 阈值(sql执行时间超过此时间单位（秒），就会触发系统日志记录)
  Write:
    Host: 192.168.3.88
    DataBase: mall-boot
    Port: 15432
    Prefix:
    User: kyle
    Pass: "123123"
    Charset: utf8
    SetMaxIdleConn: 10
    SetMaxOpenConn: 128
    SetConnMaxLifetime: 60
  Read:
    Host: 192.168.3.88
    DataBase: mall-boot
    Port: 15432
    Prefix:
    User: kyle
    Pass: "123123"
    Charset: utf8
    SetMaxIdleConn: 10
    SetMaxOpenConn: 128
    SetConnMaxLifetime: 60

CacheConf:
  - Host: 192.168.3.88:16379
    Pass:

Log:
  Mode: file
  Path: ../../../logs/rpc-pms

#Prometheus:
#  Host: 0.0.0.0
#  Port: 10102
#  Path: /metrics

#Telemetry:
#  Name: pms.rpc
#  Endpoint: http://192.168.3.88:14268/api/traces
#  Sampler: 1.0
#  Batcher: jaeger