// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: pb/oms.proto

package omsPb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OmsClient is the client API for Oms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OmsClient interface {
	// -------
	OrderGet(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Order, error)
	OrderList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*OrderListResp, error)
	OrderAdd(ctx context.Context, in *OrderAddReq, opts ...grpc.CallOption) (*SuccessIdResp, error)
	OrderUpdate(ctx context.Context, in *OrderUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error)
}

type omsClient struct {
	cc grpc.ClientConnInterface
}

func NewOmsClient(cc grpc.ClientConnInterface) OmsClient {
	return &omsClient{cc}
}

func (c *omsClient) OrderGet(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/omsPb.oms/OrderGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) OrderList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*OrderListResp, error) {
	out := new(OrderListResp)
	err := c.cc.Invoke(ctx, "/omsPb.oms/OrderList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) OrderAdd(ctx context.Context, in *OrderAddReq, opts ...grpc.CallOption) (*SuccessIdResp, error) {
	out := new(SuccessIdResp)
	err := c.cc.Invoke(ctx, "/omsPb.oms/OrderAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omsClient) OrderUpdate(ctx context.Context, in *OrderUpdateReq, opts ...grpc.CallOption) (*SuccessResp, error) {
	out := new(SuccessResp)
	err := c.cc.Invoke(ctx, "/omsPb.oms/OrderUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OmsServer is the server API for Oms service.
// All implementations must embed UnimplementedOmsServer
// for forward compatibility
type OmsServer interface {
	// -------
	OrderGet(context.Context, *IdReq) (*Order, error)
	OrderList(context.Context, *ListReq) (*OrderListResp, error)
	OrderAdd(context.Context, *OrderAddReq) (*SuccessIdResp, error)
	OrderUpdate(context.Context, *OrderUpdateReq) (*SuccessResp, error)
	mustEmbedUnimplementedOmsServer()
}

// UnimplementedOmsServer must be embedded to have forward compatible implementations.
type UnimplementedOmsServer struct {
}

func (UnimplementedOmsServer) OrderGet(context.Context, *IdReq) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderGet not implemented")
}
func (UnimplementedOmsServer) OrderList(context.Context, *ListReq) (*OrderListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderList not implemented")
}
func (UnimplementedOmsServer) OrderAdd(context.Context, *OrderAddReq) (*SuccessIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderAdd not implemented")
}
func (UnimplementedOmsServer) OrderUpdate(context.Context, *OrderUpdateReq) (*SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderUpdate not implemented")
}
func (UnimplementedOmsServer) mustEmbedUnimplementedOmsServer() {}

// UnsafeOmsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OmsServer will
// result in compilation errors.
type UnsafeOmsServer interface {
	mustEmbedUnimplementedOmsServer()
}

func RegisterOmsServer(s grpc.ServiceRegistrar, srv OmsServer) {
	s.RegisterService(&Oms_ServiceDesc, srv)
}

func _Oms_OrderGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).OrderGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omsPb.oms/OrderGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).OrderGet(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_OrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).OrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omsPb.oms/OrderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).OrderList(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_OrderAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).OrderAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omsPb.oms/OrderAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).OrderAdd(ctx, req.(*OrderAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Oms_OrderUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmsServer).OrderUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omsPb.oms/OrderUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmsServer).OrderUpdate(ctx, req.(*OrderUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Oms_ServiceDesc is the grpc.ServiceDesc for Oms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Oms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omsPb.oms",
	HandlerType: (*OmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderGet",
			Handler:    _Oms_OrderGet_Handler,
		},
		{
			MethodName: "OrderList",
			Handler:    _Oms_OrderList_Handler,
		},
		{
			MethodName: "OrderAdd",
			Handler:    _Oms_OrderAdd_Handler,
		},
		{
			MethodName: "OrderUpdate",
			Handler:    _Oms_OrderUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/oms.proto",
}
